"use client";
// AUTO-GENERATED BY KODAGEN — DO NOT EDIT OR REPLACE THIS FILE.
// Floating WhatsApp chat button. Self-configuring: reads the chat link
// from the site's live data and renders NOTHING until the owner has
// configured one — so it must always stay mounted in the root layout.
import { useEffect, useState } from "react";
import { getKodagenLiveData } from "../lib/kodagen-live";

export default function WhatsAppFloat() {
  const [link, setLink] = useState<string | null>(null);
  const [hover, setHover] = useState(false);

  useEffect(() => {
    let alive = true;
    getKodagenLiveData()
      .then((d) => { if (alive) setLink(d.whatsapp_link); })
      .catch(() => {});
    return () => { alive = false; };
  }, []);

  if (!link) return null;

  return (
    <a
      href={link}
      target="_blank"
      rel="noopener noreferrer"
      aria-label="Chat with us on WhatsApp"
      onMouseEnter={() => setHover(true)}
      onMouseLeave={() => setHover(false)}
      style={{
        position: "fixed",
        right: "1.25rem",
        bottom: "1.25rem",
        zIndex: 2147483000,
        width: "3.5rem",
        height: "3.5rem",
        borderRadius: "9999px",
        background: "#25D366",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        boxShadow: "0 8px 24px rgba(0,0,0,0.28)",
        transform: hover ? "scale(1.08)" : "scale(1)",
        transition: "transform 160ms ease",
      }}
    >
      <svg viewBox="0 0 32 32" width="30" height="30" fill="#fff" aria-hidden="true">
        <path d="M16.004 4.667c-6.253 0-11.337 5.084-11.337 11.336 0 1.999.523 3.95 1.516 5.671L4.667 27.333l5.792-1.486a11.29 11.29 0 0 0 5.541 1.449h.005c6.252 0 11.336-5.084 11.336-11.336 0-3.029-1.179-5.876-3.32-8.017a11.263 11.263 0 0 0-8.017-3.276zm0 20.723h-.004a9.4 9.4 0 0 1-4.788-1.311l-.344-.204-3.437.882.918-3.352-.224-.344a9.394 9.394 0 0 1-1.442-5.018c0-5.198 4.23-9.428 9.432-9.428a9.37 9.37 0 0 1 6.665 2.763 9.37 9.37 0 0 1 2.759 6.669c0 5.198-4.23 9.428-9.428 9.428zm5.171-7.06c-.283-.142-1.676-.827-1.936-.921-.26-.095-.449-.142-.638.141-.188.284-.732.922-.897 1.11-.165.19-.33.213-.614.072-.283-.142-1.196-.441-2.278-1.406-.842-.751-1.41-1.678-1.576-1.961-.165-.284-.017-.437.125-.578.127-.127.283-.331.425-.497.142-.165.189-.283.283-.472.095-.189.048-.354-.023-.496-.071-.142-.638-1.537-.874-2.105-.23-.553-.464-.478-.638-.487l-.543-.01a1.04 1.04 0 0 0-.756.355c-.26.284-.992.969-.992 2.364s1.015 2.742 1.157 2.931c.141.189 1.998 3.051 4.841 4.279.677.292 1.205.466 1.617.597.679.216 1.297.185 1.786.112.545-.081 1.676-.685 1.912-1.347.236-.661.236-1.228.165-1.347-.07-.118-.26-.189-.543-.33z"/>
      </svg>
    </a>
  );
}
