// AUTO-GENERATED BY KODAGEN — DO NOT EDIT OR REPLACE THIS FILE.
// Live partner content: the products/payment links, WhatsApp chat link and
// SEO fields on this site are managed through the Kodagen Partner API and
// served from the platform at runtime. Rendering from this module is what
// makes owner updates appear on the live site without a rebuild.

export interface KodagenProduct {
  id: string;
  title: string;
  description: string | null;
  /** Minor currency unit (kobo/cents) — divide by 100 for display. */
  price_kobo: number | null;
  currency: string;
  image_url: string | null;
  /** The owner's checkout URL for this product — Buy CTAs link here. */
  payment_link: string | null;
}

export interface KodagenLiveData {
  products: KodagenProduct[];
  whatsapp_link: string | null;
  seo: { title?: string; description?: string; keywords?: string[] } | null;
  updated_at: string | null;
}

const DATA_URL = "https://kodagen.com/api/public/partner-sites/2c58abc8-052c-420d-b893-103c380e0780/data";
const INQUIRY_URL = "https://kodagen.com/api/public/partner-sites/2c58abc8-052c-420d-b893-103c380e0780/inquiries";

const EMPTY: KodagenLiveData = { products: [], whatsapp_link: null, seo: null, updated_at: null };

/**
 * Fetch the site's live content. Safe everywhere: in server components the
 * result is ISR-cached (~60s); in the browser it's a plain CORS fetch. Any
 * failure returns an empty catalog so the site never crashes on a network
 * blip — sections should render their built-in fallback copy when
 * products is empty.
 */
export async function getKodagenLiveData(): Promise<KodagenLiveData> {
  try {
    const res = await fetch(DATA_URL, { next: { revalidate: 60 } } as RequestInit);
    if (!res.ok) return EMPTY;
    const data = (await res.json()) as Partial<KodagenLiveData>;
    return {
      products: Array.isArray(data.products) ? (data.products as KodagenProduct[]) : [],
      whatsapp_link: typeof data.whatsapp_link === "string" ? data.whatsapp_link : null,
      seo: data.seo && typeof data.seo === "object" ? data.seo : null,
      updated_at: typeof data.updated_at === "string" ? data.updated_at : null,
    };
  } catch {
    return EMPTY;
  }
}

/** Format a price_kobo value for display (e.g. 2500000 NGN → "₦25,000"). */
export function formatKodagenPrice(priceKobo: number | null, currency: string): string {
  if (priceKobo == null) return "";
  const major = priceKobo / 100;
  try {
    return new Intl.NumberFormat("en-NG", {
      style: "currency",
      currency: currency || "NGN",
      maximumFractionDigits: major % 1 === 0 ? 0 : 2,
    }).format(major);
  } catch {
    return `${currency} ${major.toLocaleString()}`;
  }
}

export interface KodagenInquiryFields {
  name?: string;
  email?: string;
  phone?: string;
  message: string;
  /** Optional: the KodagenProduct.id the visitor asked about. */
  product_id?: string;
  /** Optional: the page path the form lives on. */
  page?: string;
}

/**
 * Submit a visitor inquiry to the site owner. Returns {ok} — show the
 * form's success state ONLY when ok is true.
 */
export async function submitKodagenInquiry(fields: KodagenInquiryFields): Promise<{ ok: boolean }> {
  try {
    const res = await fetch(INQUIRY_URL, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(fields),
    });
    return { ok: res.ok };
  } catch {
    return { ok: false };
  }
}
